branch protection test workflow
zeelz/zeelz-developer pull request #1
Opened 2023-11-16 23:28 UTC by zeelz

testing branch protection with workflow

2023-11-19 02:26 UTC, zeelz commented
Good to go

2023-11-19 04:42 UTC, jprodyx approved these changes
Good!

2023-11-19 04:45 UTC, jprodyx requested changes
Look at L93 for possible improvement

2023-11-19 06:00 UTC, jprodyx approved these changes
Approved

2023-11-19 06:08 UTC, merged

2024-01-10 02:30 UTC, zeelz commented on .github/workflows/cd.yml
> +    workflows: ["Docker Image CI__DISABLE_WKFLW"]
comment 1